version: '3.3'
services:
  connective-socket:
    container_name: connective-socket
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: npm run start:dev
    ports:
      - "3001:3001"
    env_file:
      - .env
      