name: daily-cron
on:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://connective-app.vercel.app/api/messages/unread-messages-mailer' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
